// <auto-generated />
using System;
using DeptHieracy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeptHieracy.Migrations
{
    [DbContext(typeof(DepartmentContext))]
    partial class DepartmentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeptHieracy.Models.Dept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeptNameName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Parent_Dept_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Parent_Dept_id");

                    b.ToTable("Depts");
                });

            modelBuilder.Entity("DeptHieracy.Models.Dept", b =>
                {
                    b.HasOne("DeptHieracy.Models.Dept", "Parent_dept")
                        .WithMany()
                        .HasForeignKey("Parent_Dept_id");

                    b.Navigation("Parent_dept");
                });
#pragma warning restore 612, 618
        }
    }
}
